### ISSUE TITLE
Getting strange error: subject may not be empty [subject-empty]

### ISSUE THREAD

**Issue by moltar** [KnisterPeter/vscode-commitizen#313]
This started a few days ago all of a sudden.

Here's the full output:

```
Command failed with exit code 1: git commit -m "refactor: to use a constant name for the handler fn name"
husky > pre-commit (node v12.16.0)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.(js|ts)
[STARTED] Running tasks for package.json
[SKIPPED] No staged files match package.json
[STARTED] eslint --fix
[SUCCESS] eslint --fix
[SUCCESS] Running tasks for *.(js|ts)
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SUCCESS] Applying modifications...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...
husky > commit-msg (node v12.16.0)
⧗   input: "refactor: to use a constant name for the handler fn name"
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
```

If I run exactly the same command from CLI it works just fine:

```
git commit -m "refactor: to use a constant name for the handler fn name"
```

Any ideas?

Thanks.

**Comment by moltar** [comment]
Just to confirm, when downgraded to `v0.8.4` -- the error went away.

**Comment by KnisterPeter** [comment]
@moltar If you open the commitizen output channel in vscode, what do you see at this message: `About to commit `?

**Comment by moltar** [comment]
```
Commitizen support started
About to commit 'fix: test commz'
Command failed with exit code 1: git commit -m "fix: test commz"
husky > pre-commit (node v12.16.0)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.(js|ts)
[STARTED] Running tasks for package.json
[SKIPPED] No staged files match package.json
[STARTED] eslint --fix
[SUCCESS] eslint --fix
[SUCCESS] Running tasks for *.(js|ts)
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SUCCESS] Applying modifications...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...
husky > commit-msg (node v12.16.0)
⧗   input: "fix: test commz"
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
Error: Command failed with exit code 1: git commit -m "fix: test commz"
husky > pre-commit (node v12.16.0)
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.(js|ts)
[STARTED] Running tasks for package.json
[SKIPPED] No staged files match package.json
[STARTED] eslint --fix
[SUCCESS] eslint --fix
[SUCCESS] Running tasks for *.(js|ts)
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SUCCESS] Applying modifications...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...
husky > commit-msg (node v12.16.0)
⧗   input: "fix: test commz"
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky > commit-msg hook failed (add --no-verify to bypass)
    at makeError (/Users/user/.vscode/extensions/knisterpeter.vscode-commitizen-0.9.2/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/user/.vscode/extensions/knisterpeter.vscode-commitizen-0.9.2/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

```

**Comment by JokerArvin** [comment]
The same question,I noticed that I have quotes in my submission.

**Comment by Lakston** [comment]
Confirming this issue on vscode latest and plugin latest

`Subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] `

**Comment by alonesuperman** [comment]
same issue here

**Comment by whitemiaool** [comment]
same issue, latest version
Command failed with exit code 1: git commit -m "fix(1): 1" husky > commit-msg (node v12.4.0) ⧗ input: "fix(1): 1" ✖ subject may not be empty [subject-empty] ✖ type may not be empty [type-empty] ✖ found 2 problems, 0 warnings ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint husky > commit-msg hook failed (add --no-verify to bypass)

**Comment by KnisterPeter** [comment]
@shipjs prepare

**Comment by KnisterPeter** [comment]
Thanks for all the feedback and sorry for the inconvenience. I'll create a new release with the fix.
