### ISSUE TITLE
[bug] commit error when workspace has multi repo

### ISSUE THREAD

**Issue by SterbenJ** [KnisterPeter/vscode-commitizen#660]
I try to commit change at `apps/app-test` in workspace that has multi repo in `packages` and `apps` like this:

```
└─packages
   ├─....
   └─package-a
└─apps
   ├─app-test
   └─app-dev
```

and then

```
Commitizen support started
About to commit 'feat(test): 2333'
Command failed with exit code 128: git commit -m "feat(test): 2333"
fatal: not a git repository (or any of the parent directories): .git
Error: Command failed with exit code 128: git commit -m "feat(test): 2333"
fatal: not a git repository (or any of the parent directories): .git
    at makeError (d:\IDE\vscode\data\extensions\knisterpeter.vscode-commitizen-1.0.2\node_modules\execa\lib\error.js:60:11)
    at handlePromise (d:\IDE\vscode\data\extensions\knisterpeter.vscode-commitizen-1.0.2\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by SterbenJ** [comment]
sth wrong when determining the root path of the repo i guess

**Comment by KnisterPeter** [comment]
@SterbenJ Thanks for reporting. Any PR to fix this is appreciated.
